config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root           'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'svelte' => 'static_pages#svelte'
  resources :dishes
  resources :dish_days
  resources :today_menus
  resources :week_plans
  resources :users
  resources :suggested_dishes do
    member do
      post :upgrade
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord

  has_many :dish_days, dependent: :destroy
  validates :name, presence: true, length: {in: 3..50}
  validate :picture_size
  mount_uploader :picture, PictureUploader

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/models/dish_day.rb
class DishDay < ApplicationRecord

  belongs_to :dish

  validates :day, :dish, presence: true
  validate :not_have_passed, if: :day?, on: :create

  scope :dish_of_the_day, -> { where(day: Date.today, dish_of_the_day: true) }

  private

  def not_have_passed
    if day < Date.today
      errors.add(:day, "can't be in the past")
    end
  end
end

app/models/suggested_dish.rb
class SuggestedDish < ApplicationRecord

  validates :name, presence: true, length: {in: 3..50}
  validates :comment, presence: true, length: {in: 3..250}
  default_scope {order('created_at DESC')}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, length: {in: 3..50}, allow_nil: true
  
  validate :picture_size
  mount_uploader :picture, PictureUploader

  private

  def picture_size
    if picture.size > 5.megabytes
     errors.add(:picture, "should be less than 5MB")
    end
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:picture, :name, :remote_picture_url])
  end
end

app/controllers/dish_days_controller.rb
class DishDaysController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_default_date
  
  def new
    @dish_day = DishDay.new
  end
  
  def create
    @dish_day = DishDay.new(dish_day_params)
    if @dish_day.save
      session[:last_used_date] = @dish_day.day
      flash[:success] = "Date has been assigned"
      redirect_to new_dish_day_path
    else
      render "new"
    end
  end
  
  def edit
    @dish_day = DishDay.find(params[:id])
  end
  
  def update
    @dish_day = DishDay.find(params[:id])
    if @dish_day.update_attributes(dish_day_params)
      flash[:success] = "Menu item have been updated"
      redirect_to week_plans_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @dish_day = DishDay.find(params[:id]).destroy
    flash[:success] = "Menu item deleted"
    redirect_to week_plans_path
  end
  
  private
  
  def dish_day_params
    params.require(:dish_day).permit(:dish_id, :day, :dish_of_the_day)
  end
  
  def set_default_date
    @default_date ||= if session[:last_used_date].present? && Date.parse(session[:last_used_date]) > Date.today
      Date.parse(session[:last_used_date])
    else
      Date.today
    end
  end
  
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @dishes = Dish.all.order(updated_at: :desc)
  end
  
  def new
    @dish = Dish.new
  end
  
  def create
    @dish = Dish.new(dish_params)
    if @dish.save
      flash[:success] = "Dish has been created successfully (I hope)"
      redirect_to new_dish_path
    else
      render "new"
    end
  end
  
  def edit
    @dish = Dish.find(params[:id])
  end
  
  def update
    @dish = Dish.find(params[:id])
    if @dish.update_attributes(dish_params)
      flash[:success] = "Dish have been updated"
      redirect_to dishes_path
    else
      render 'edit'
    end
  end
  
  def destroy
    #binding.pry
    @dish = Dish.find(params[:id]).destroy
    flash[:success] = "Dish deleted"
    redirect_to dishes_path
  end
  
  private
  
  def dish_params
    params.require(:dish).permit(:name, :picture, :remote_picture_url)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @dish_of_the_day = DishDay.dish_of_the_day.first
    @suggested_dish  = SuggestedDish.new
  end

  def about; end

  def svelte; end
end

app/controllers/today_menus_controller.rb
class TodayMenusController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @dish_days = DishDay.where(day: Date.today)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
  end
  
  
  
  
  private

#     def user_params
#       params.require(:user).permit(:name, :email, :password, :password_confirmation)
#     end

  
  
end

app/controllers/week_plans_controller.rb
class WeekPlansController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @week_plan = DishDay.where(day: Date.today.all_week)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  #Returns the full titile on a per-page basis
  def full_title(page_title = '')
    base_title = "Menu Tulentsevyh"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = "The form contains #{pluralize(resource.errors.count, "error")}"

    html = <<-HTML
    <div id="error_explanation">
      <div class="alert alert-danger">
        #{sentence}
      </div>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.present?
  end

end

app/helpers/dish_days_helper.rb
module DishDaysHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suggested_dishes_helper.rb
module SuggestedDishesHelper
end

app/helpers/today_menu_helper.rb
module TodayMenuHelper
end

app/helpers/week_plans_helper.rb
module WeekPlansHelper
end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))  %> </title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'hello_svelte' %>
    <%= csrf_meta_tags %>

    <%= render 'layouts/shim' %>
  </head>
  <body>

    <%= render 'shared/navbar' if user_signed_in?%>

    <div class="container">
      <div class="container" id="flash_messages">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message.html_safe, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>

      <% if request.original_url == root_url %>
        <div>
          <%= image_tag(asset_path("home.jpg"), alt: "Our logo", class: 'img-responsive img-rounded') %>
        </div>
      <% end %>
      <%= render 'shared/navmenu'%>

      <%= yield %>

    </div>
  </body>
</html>

app/views/shared/_default_home.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="center jumbotron">
      <h2>Welcome to Menu Tulentsevyh</h2>
      <p>Here will be a text <strong>about</strong> the app</p>
    </div>
  </div>
  <div class="col-md-3">
    <h4>Be a chief and enjoy your dinner every day!</h4>
    <ul class="list-unstyled">
      <li class="bg-primary text-center"><%= link_to "Click here to sign up!", new_user_registration_path, style: "color: white", id:"sign-up"%>,</li>
      <li class="text-center"><%= link_to "Click here to sign in!", new_user_session_path, id:"sign-in" %></li>
    </ul>
    <%= render Dish.first %>
  </div>
</div>

app/views/shared/_dish_of_the_day.html.erb
  <img class="img-thumbnail" src="<%= @dish_of_the_day.dish.picture %>" />
  <span class="name"><h4><%= @dish_of_the_day.dish.name %></h4></span>

app/views/shared/_error_messages.html.erb
<div id="error_explanation">
  <% if object.errors.any? %>
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_home_for_users.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="center jumbotron">
      <h2>Dish of the day:</h2>
      <% if @dish_of_the_day %>
        <div class="container" id="dish_of_the_day">
          <%= render "shared/dish_of_the_day"%>
        </div>
      <% else %>
        <h3 class="alert alert-info">Try all delicious dishes!</h3>
      <% end %>
      <div class="pull-right">
        <%= link_to  "See whole menu >", today_menus_path %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <h4>Here you can press a button and suggest a dish.</h4>
    <input type="button" id='suggest_dish_modal' class="btn btn-primary" data-toggle="modal" data-target="#suggested_dishes_modal" value="Do it!" />
  </div>
</div>


<div class="modal fade" id="suggested_dishes_modal" title="Suggest a dish!">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Suggest something tasty!</h4>
      </div>
      <div class="modal-body">
        <%= render "shared/suggested_dish_form" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_login_form.html.erb
<%= form_for(:user, :url => session_path(:user), :html => {class: "form-inline"}) do |f| %>
  <div class="form-group">
    <%= f.text_field :email, autofocus: true, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
  </div>
  <div class="checkbox">
    <%= f.check_box :remember_me, class: "checkbox inline" %>
    <%= f.label :remember_me %>
  </div>
  <%= f.submit 'Sign in' , class:"btn btn-primary"%>
  <%= link_to "Forgot your password?", new_password_path(:user), class:"btn btn-default" %>
<% end %>

app/views/shared/_navbar.html.erb
  <nav class="navbar-default">
    <div class="container-fluid">
      <% if current_user %>
      <span class="navbar-text">
        Me logged in: </span>
        <%= link_to current_user.email, user_path(current_user.id),class:"navbar-text"%>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"navbar-text" %>
        <%= link_to 'Svelte', svelte_path, class:"navbar-text"%>
    <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Dish list", dishes_path %></li>
        <li><%= link_to "Add dish", new_dish_path %></li>
        <li><%= link_to "Create menu", new_dish_day_path %></li>
        <li><%= link_to "Suggested dish list", suggested_dishes_path %></li>
      </ul>
    </div>
  </nav>

app/views/shared/_navmenu.html.erb
<div class="container">
  <nav>
    <ul class="nav navbar-nav navbar-left">
      <% if user_signed_in?%>
        <li><%= link_to "Today's Menu", today_menus_path %></li>
        <li><%= link_to "Week plan", week_plans_path %></li>
        <li><%= link_to "Shopping list", '#' %></li>
        <li><%= link_to "Feedback", '#' %></li>
      <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/shared/_suggested_dish_form.html.erb
<div class="container">
  <%= form_for(@suggested_dish, remote: true, html: {id: "add_suggested_dish_form"}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control for-dishes", placeholder: "Enter a name"%>
    </div>
    <div class="form-group">
        <%= f.label :comment, class: "control-label" %>
        <%= f.text_area :comment, class: "form-control for-dishes", placeholder: "Leave here your comment..." %>
        <p class="help-block">You can type up to 255 characters</p>
    </div>
    <%= f.submit "Save", name: "commit", class: "btn btn-primary" %>
  <% end %>
</div> 