config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}
  root           'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'svelte' => 'static_pages#svelte'
  resources :dishes
  resources :dish_days
  resources :today_menus
  resources :week_plans
  resources :users
  resources :suggested_dishes do
    member do
      post :upgrade
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord

  has_many :dish_days, dependent: :destroy
  validates :name, presence: true, length: {in: 3..50}
  validate :picture_size
  mount_uploader :picture, PictureUploader

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/models/dish_day.rb
class DishDay < ApplicationRecord

  belongs_to :dish

  validates :day, :dish, presence: true
  validate :not_have_passed, if: :day?, on: :create

  scope :dish_of_the_day, -> { where(day: Date.today, dish_of_the_day: true) }

  private

  def not_have_passed
    if day < Date.today
      errors.add(:day, "can't be in the past")
    end
  end
end

app/models/suggested_dish.rb
class SuggestedDish < ApplicationRecord

  validates :name, presence: true, length: {in: 3..50}
  validates :comment, presence: true, length: {in: 3..250}
  default_scope {order('created_at DESC')}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, length: {in: 3..50}, allow_nil: true
  
  validate :picture_size
  mount_uploader :picture, PictureUploader

  private

  def picture_size
    if picture.size > 5.megabytes
     errors.add(:picture, "should be less than 5MB")
    end
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:picture, :name, :remote_picture_url])
  end
end

app/controllers/dish_days_controller.rb
class DishDaysController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_default_date
  
  def new
    @dish_day = DishDay.new
  end
  
  def create
    @dish_day = DishDay.new(dish_day_params)
    if @dish_day.save
      session[:last_used_date] = @dish_day.day
      flash[:success] = "Date has been assigned"
      redirect_to new_dish_day_path
    else
      render "new"
    end
  end
  
  def edit
    @dish_day = DishDay.find(params[:id])
  end
  
  def update
    @dish_day = DishDay.find(params[:id])
    if @dish_day.update_attributes(dish_day_params)
      flash[:success] = "Menu item have been updated"
      redirect_to week_plans_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @dish_day = DishDay.find(params[:id]).destroy
    flash[:success] = "Menu item deleted"
    redirect_to week_plans_path
  end
  
  private
  
  def dish_day_params
    params.require(:dish_day).permit(:dish_id, :day, :dish_of_the_day)
  end
  
  def set_default_date
    @default_date ||= if session[:last_used_date].present? && Date.parse(session[:last_used_date]) > Date.today
      Date.parse(session[:last_used_date])
    else
      Date.today
    end
  end
  
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @dishes = Dish.all.order(updated_at: :desc)
  end
  
  def new
    @dish = Dish.new
  end
  
  def create
    @dish = Dish.new(dish_params)
    if @dish.save
      flash[:success] = "Dish has been created successfully (I hope)"
      redirect_to new_dish_path
    else
      render "new"
    end
  end
  
  def edit
    @dish = Dish.find(params[:id])
  end
  
  def update
    @dish = Dish.find(params[:id])
    if @dish.update_attributes(dish_params)
      flash[:success] = "Dish have been updated"
      redirect_to dishes_path
    else
      render 'edit'
    end
  end
  
  def destroy
    #binding.pry
    @dish = Dish.find(params[:id]).destroy
    flash[:success] = "Dish deleted"
    redirect_to dishes_path
  end
  
  private
  
  def dish_params
    params.require(:dish).permit(:name, :picture, :remote_picture_url)
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  before_action :authenticate_user!
  
  
  
  protected
  
  def update_resource(recource, params)
    resource.update_without_password(params)
  end
  
  def after_update_path_for(resource)
    user_path(resource)
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @dish_of_the_day = DishDay.dish_of_the_day.first
    @suggested_dish  = SuggestedDish.new
  end

  def about; end

  def svelte; end
end

app/controllers/suggested_dishes_controller.rb
class SuggestedDishesController < ApplicationController
  
  before_action :authenticate_user!
  
  def new
    @suggested_dish = SuggestedDish.new
    super
  end

  def create
    @suggested_dish = SuggestedDish.new(suggested_dish_params)
    respond_to do |format|
      if @suggested_dish.save
        format.js { flash.now[:success] = "You have suggested <strong>#{@suggested_dish.name}</strong>."}
        SuggestedDishMailer.new_suggested_dish(@suggested_dish).deliver_now
      else
        format.js
      end
    end
  end
  
  def index
    @suggested_dishes = SuggestedDish.all
  end
  
  def edit
    @suggested_dish = SuggestedDish.find(params[:id])
  end
  
  def update
    @suggested_dish = SuggestedDish.find(params[:id])
    if @suggested_dish.update_attributes(suggested_dish_params)
      flash[:success] = "Suggested dish have been updated"
      redirect_to suggested_dishes_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @suggested_dish = SuggestedDish.find(params[:id]).destroy
    flash[:success] = "Suggested dish deleted"
    redirect_to suggested_dishes_path
  end
  
  def upgrade
    suggested_dish = SuggestedDish.find(params[:id])
    dish = make_dish(suggested_dish)
    dish.save!
    redirect_to edit_dish_path(dish)
  end


  private

  def suggested_dish_params
    params.require(:suggested_dish).permit(:id, :name, :comment)
  end
  
  def make_dish(suggested_dish)
    Dish.new(name: suggested_dish.name)
  end

end

app/controllers/today_menus_controller.rb
class TodayMenusController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @dish_days = DishDay.where(day: Date.today)
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
  end
  
  
  
  
  private

#     def user_params
#       params.require(:user).permit(:name, :email, :password, :password_confirmation)
#     end

  
  
end

app/controllers/week_plans_controller.rb
class WeekPlansController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @week_plan = DishDay.where(day: Date.today.all_week)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  #Returns the full titile on a per-page basis
  def full_title(page_title = '')
    base_title = "Menu Tulentsevyh"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = "The form contains #{pluralize(resource.errors.count, "error")}"

    html = <<-HTML
    <div id="error_explanation">
      <div class="alert alert-danger">
        #{sentence}
      </div>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.present?
  end

end

app/helpers/dish_days_helper.rb
module DishDaysHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suggested_dishes_helper.rb
module SuggestedDishesHelper
end

app/helpers/today_menu_helper.rb
module TodayMenuHelper
end

app/helpers/week_plans_helper.rb
module WeekPlansHelper
end

app/views/dish_days/_dish_days_form.html.erb
<div class="container">
  <%= form_for(@dish_day, html: {multiupart: true, class:"form-horizontal" }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label "Choose date", class: "control-label"%>
      <div class="form-inline">
        <%= f.date_select :day, {order: [:day, :month, :year], default: @default_date}, {class: "form-control input-sm"} %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :dish_id, class: "control-label"%>
      <%= f.collection_select(:dish_id, Dish.all, :id, :name, {}, class: "form-control for-dishes")%>
      <div class="checkbox">
        <%= f.label :dish_of_the_day, class: "checkbox inline" do %>
          <%= f.check_box :dish_of_the_day %>
          <span>That's a dish of the day!</span>
        <% end %>
      </div>
    </div>
    <div class="form-group">
          <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/dish_days/edit.html.erb
<% provide(:title, "Edit menu item") %>

<h1>Change day or dish here</h1>
<%= render 'dish_days_form'%>

app/views/dish_days/new.html.erb
<% provide(:title, "Create menu") %>

<h1>Here you can assign dates to dishes</h1>
  
<%= render 'dish_days_form'%>

app/views/dishes/_dish.html.erb
<div class="thumbnail">
  <img src="<%= dish.picture %>" />
  <div class="caption">
    <h5 class="name center"><%= dish.name.capitalize %></h5>
  </div>
</div>

app/views/dishes/_dish_add_form.html.erb
<%= form_for(@dish, html: {multiupart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name, 'Dish', class: "control-label" %>
    <%= f.text_field :name, class: "form-control for-dishes",  id: "for-dishes", placeholder: "Enter a name"%>
  </div>
  <div class="form-group">
    <%= f.label :picture, class: "control-label" %>
    <span class="help-block">Choose your file or paste a url from the internets</span>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    <span class="help-block">Choose a file up to 5MB</span>

    <%= f.text_field :remote_picture_url, class: "form-control for-dishes", id: "dish_remote_picture_url", placeholder: "Paste a URL here" %>
  </div>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>


<script type="text/javascript">
  $('#dish_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/dishes/edit.html.erb
<% provide(:title, "Edit dish") %>

<h1>Dish can be better!</h1>

<div class="row">
  <div class="col-md-3">
    <span><strong>Current picture:</strong></span>
    <img class="img-rounded" src="<%= @dish.picture.presence || asset_path('b2.png') %>" />
  </div>
  <div class="col-md-3 col-md-offset-1">
    <%= render 'dish_add_form' %>
  </div>
</div>
<%= link_to '< Back to dishes', dishes_path %>

app/views/dishes/index.html.erb
<% provide(:title, "Dish list") %>

<h2>Here I can view list of all dishes</h2>

<table class="table borderless">
  
  <% @dishes.in_groups_of(3).each do |row| %>
    <tr>
      <% row.each do |dish| %>
        <td>
          <% if dish %>
            <div class="dish-cells center" id="dish-<%= dish.id %>">
              <button type="button" class="pull-right close" aria-label="Close" id="close-button">
                <%= link_to "&times;".html_safe, dish, method: :delete %>
              </button>
              <img class="img-thumbnail" src="<%= dish.picture %>" />
              <span class="name clearfix"><%= link_to dish.name, edit_dish_path(dish.id)%></span>
            </div>              
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/dishes/new.html.erb
<% provide(:title, "Adding new dishes") %>


  <h2>Here I can add new dishes</h2>
  <%= render "dish_add_form" %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>Tulenmenu about</h1>
<p>Here will be some text <strong>about</strong> the app</p>

app/views/static_pages/home.html.erb
<% if user_signed_in?%>

  <%= render 'shared/home_for_users'%>
<% else %>
  <%= render 'shared/default_home'%>
<% end %>

app/views/static_pages/svelte.html.erb
<div class="center jumbotron">
  <div id='svelte_app'></div>
</div>

app/views/suggested_dishes/_suggested_dish.html.erb
<li class="list-group-item"  id="suggested-dish-<%= suggested_dish.id %>">
 
  <div class="pull-left">
    <%= link_to "Make a dish", upgrade_suggested_dish_path(suggested_dish), method: :post, class:"btn btn-default"%>
  </div>
  <div class="suggested-dish-content">
    <p class="name"><%= link_to suggested_dish.name.capitalize, edit_suggested_dish_path(suggested_dish.id) %>: 
    <span class="comment"><%= suggested_dish.comment%></span></p>
  </div>
  <button type="button" class="close" aria-label="Close" id="close-button">
   <%= link_to "&times;".html_safe, suggested_dish, method: :delete %>
  </button>

</li>

app/views/suggested_dishes/create.js.erb
<% if @suggested_dish.persisted? %>
  $('#suggested_dish_name').val('');
  $('#suggested_dish_comment').val('');
  $('<div></div>').addClass("alert alert-success").html('<%= flash.now[:success].html_safe %>').appendTo($('#flash_messages')) 
  $('#suggested_dishes_modal').modal('hide');
<% else %>
  var errors = <%= @suggested_dish.errors.full_messages.to_json.html_safe %>;
  var errorsHtml = $('<ul></ul>');
  errors.forEach(function(err) {
    $('<li></li>').html(err).appendTo(errorsHtml);
  });
  $('#error_explanation').html(errorsHtml);
<% end %>

app/views/suggested_dishes/edit.html.erb
<% provide(:title, "Edit suggested dish") %>

<h1>You can make this real!</h1>
<div class="container">
  <%= form_for(@suggested_dish, html: {id: "add_suggested_dish_form"}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control for-dishes", placeholder: "Enter a name"%>
    </div>
    <div class="form-group">
        <%= f.label :comment, class: "control-label" %>
        <%= f.text_area :comment, class: "form-control for-dishes", placeholder: "Leave here your comment..." %>
        <p class="help-block">You can type up to 255 characters</p>
    </div>
    <%= f.submit "Save", name: "commit", class: "btn btn-primary" %>
  <% end %>
</div> 

app/views/suggested_dishes/index.html.erb
<% provide(:title, "Suggested dish list") %>
  
<h2>These are the dishes you have suggested</h2>

<ul class="list-group" id="suggested_dishes">
    <%= render @suggested_dishes %>
</ul>

app/views/today_menus/_dish_day.html.erb
<li id="dish_day">
  <div id="today_menu">
    <img class="img-rounded" src="<%= dish_day.dish.picture %>" />
    <% if dish_day.dish_of_the_day %>
      <span class="badge">Dish of the day!</span>
    <% end %>
    <p class="text-center"><%= dish_day.dish.name %></p>
  </div>
  
</li>

app/views/today_menus/index.html.erb
<% provide(:title, "Today's menu") %>

<h1>Here you can see a menu for today</h1>
<div class="center jumbotron">
  <div class="container">
    <% if @dish_days.exists? %>
      <ul class="list-inline">
        <% @dish_days.each do |dish_day| %>
          <%= render partial: "dish_day", locals: {dish_day: dish_day} %>
        <% end %>
      </ul>
    <% else %>
      <p class="alert alert-info">Stay hungry today!</p>
    <% end %>
  </div>
  <div class="pull-right">
    <%= link_to  "See next days menu >", week_plans_path %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h2><%= @user.email%>'s page is here</h2>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <span><strong>Current avatar:</strong></span>
      <img class="img-rounded" src="<%= @user.picture %>" />
    </div>
    <div class="col-md-4 col-md-offset-1">
      <ul class="list-unstyled">
        <li><h3><%= @user.name %></h3></li>
        <li>Email: <%= @user.email %></li>
        <li>Registration date: <%= @user.created_at.strftime('%F') %></li>
      </ul>
    </div>
  </div>
  <%= link_to 'Edit user data', edit_user_registration_path %>
</div>

app/views/week_plans/_weekdish.html.erb
<li id="week-plan-dish-<%=weekdish.dish.id%>" class="week-plan-dish">
  <div class="dish-cells center">
    <button type="button" class="pull-right close" aria-label="Close" id="close-button">
      <%= link_to "&times;".html_safe, weekdish, method: :delete %>
    </button>
    <img id="for-week" class="img-rounded" src="<%= weekdish.dish.picture %>" />
    <p class="text-center"><%= link_to weekdish.dish.name, edit_dish_day_path(weekdish.id)%></p>
  </div>
</li>

app/views/week_plans/index.html.erb
<% provide(:title, "Week plan") %>

<h1>Here will be a menu for current week</h1>

<% if @week_plan.exists? %>
  <div class="container">
    <ul class="list-group">
      <% Date.today.all_week.each do |weekday| %>
        <li class="list-group-item" id="dish-day-<%= weekday %>">
          <h4><%= weekday.strftime("%A")%></h4>
          <div class="container">
            <% if @week_plan.where(day: weekday).exists? %>
              <ul class="list-inline" id="dish-day-<%= weekday %>">
                <% @week_plan.where(day: weekday).each do |weekdish| %>
                  <%= render partial: "weekdish", locals: {weekdish: weekdish} %>
                <% end %>
              </ul>
            <% else %>
              <p>no dishes for this day yet</p>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <p class="alert alert-info">No menu for this week yet!</p>
<% end %>